-- Run this in your Supabase SQL Editor to fix schema issues

-- 1. Ensure 'role' exists in profiles
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS role text DEFAULT 'user';

-- 2. Ensure 'blogs' table has all required columns
-- Adding image_url which was missing
ALTER TABLE public.blogs 
ADD COLUMN IF NOT EXISTS image_url text;

ALTER TABLE public.blogs 
ADD COLUMN IF NOT EXISTS status text DEFAULT 'published';

ALTER TABLE public.blogs 
ADD COLUMN IF NOT EXISTS views bigint DEFAULT 0;

ALTER TABLE public.blogs 
ADD COLUMN IF NOT EXISTS tags text[];

-- 3. Create categories table if not exists (for the Categories page)
CREATE TABLE IF NOT EXISTS public.categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    slug text not null,
    post_count bigint default 0,
    status text default 'active',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS on Categories
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- 5. Policies for Categories
-- Allow read access to everyone
CREATE POLICY "Categories are viewable by everyone" 
ON public.categories FOR SELECT 
USING (true);

-- Allow insert/update/delete only for admins (or authenticated users for now)
CREATE POLICY "Authenticated users can manage categories" 
ON public.categories FOR ALL 
USING (auth.role() = 'authenticated');

-- 6. Insert default categories if empty
INSERT INTO public.categories (name, slug)
VALUES 
    ('Technology', '/technology'),
    ('Lifestyle', '/lifestyle'),
    ('Design', '/design'),
    ('Business', '/business'),
    ('Founder''s Series', '/founders-series')
ON CONFLICT (name) DO NOTHING;

-- 7. Grant permissions just in case
GRANT ALL ON TABLE public.blogs TO postgres;
GRANT ALL ON TABLE public.blogs TO service_role;
