-- Create notifications table
CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint generated by default as identity primary key,
    type text not null, -- 'info', 'success', 'warning', 'error'
    message text not null,
    is_read boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Policy: Admins can view all notifications (Simplified for demo)
CREATE POLICY "Admins can view all notifications" ON public.notifications
    FOR ALL
    USING (true); -- In production, check auth.uid() and role

-- Insert dummy notifications for demo
INSERT INTO public.notifications (type, message, created_at)
VALUES
    ('info', 'Welcome to your new dashboard!', now() - interval '1 day'),
    ('success', 'Your first post reached 100 views.', now() - interval '2 hours'),
    ('warning', 'Update your profile picture.', now() - interval '5 days');
