-- Create profiles table
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  username text,
  avatar_url text,
  role text default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (id)
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

-- Create blogs table
create table public.blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  image_url text, -- URL to the cover image
  tags text[],
  author_id uuid references public.profiles(id) not null,
  status text default 'published',
  views bigint default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.blogs enable row level security;

-- Create comments table
create table public.comments (
  id bigint generated by default as identity primary key,
  content text not null,
  blog_id bigint references public.blogs(id) on delete cascade not null,
  author_id uuid references public.profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.comments enable row level security;

-- Policies (Simplified for now)
-- PUBLIC READ for everyone
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Blogs are viewable by everyone."
  on blogs for select
  using ( true );

create policy "Comments are viewable by everyone."
  on comments for select
  using ( true );

-- AUTHENTICATED INSERT/UPDATE for owners
create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

create policy "Authenticated users can create blogs."
  on blogs for insert
  with check ( auth.role() = 'authenticated' );
  -- Note: Ideally check if author_id == auth.uid()

create policy "Users can update own blogs."
  on blogs for update
  using ( auth.uid() = author_id );
  
create policy "Authenticated users can comment."
  on comments for insert
  with check ( auth.role() = 'authenticated' );
